image: python:3.12.2

stages:
  - lint
  - test
  - build

variables:
  AVAILABILITY_LISTS_SOURCE_FOLDER_URL: "source_data"

before_script:
  - apt-get update -y
  - apt-get update && apt-get install -y virtualenv
  - virtualenv venv
  - source venv/bin/activate

# lint python code
linting:
  stage: lint
  script:
    - pip install flake8
    - flake8 --ignore=E501 --exclude=venv,.venv .
  allow_failure: true
# run tests
test:
  stage: test
  script:
    - pip install -r requirements.txt
    - python -m unittest test_bench_availability_reminder.py

# create and send the remidner Emails to bench candidates
build:
  stage: build
  script:
    - echo "Value of AVAILABILITY_LISTS_SOURCE_FOLDER_URL:" ${AVAILABILITY_LISTS_SOURCE_FOLDER_URL}
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python bench_availability_reminder.py
