name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install flake8

      - name: Lint code
        run: |
          flake8 --ignore=E501 --exclude=venv,.venv .

    continue-on-error: true

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest test_bench_availability_reminder.py

  build:
    runs-on: ubuntu-latest
    needs: test
    env:
      AVAILABILITY_LISTS_SOURCE_FOLDER_URL: source_data
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.2'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python bench_availability_reminder.py
        env:
          AVAILABILITY_LISTS_SOURCE_FOLDER_URL: ${{ env.AVAILABILITY_LISTS_SOURCE_FOLDER_URL }}
